name: Compile requirements.txt

on:
  workflow_dispatch:
  push:
    paths:
      - 'requirements*.in'
      - 'requirements-compile.txt'

env:
  PYTHONUNBUFFERED: True

permissions:
  contents: read # be able to clone the repo
  id-token: write # be able to generate a JWT token to assume AWS Roles


jobs:
  generate-requirements:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "windows-2019"
          - "windows-2022"
        python-version:
            - 3.9.13
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip tools
        run: |
          python -m pip install -r requirements-compile.txt --upgrade
          pip list

      - name: Use pre-commit hook to compile requirements
        run: |
          python src/hooks/pip_tools_hook.py exit-zero compile

      - name: Upload compiled requirements
        uses: actions/upload-artifact@v3.1.2
        with:
          name: requirements--${{ matrix.python-version }}--${{ matrix.os }}
          path: "requirements-dev-${{ runner.os }}.txt"
